---
version: "2"
linters:
  # Default: standard
  default: all
  # Enable specific linter.
  enable:
    - modernize
    - wsl_v5
    - revive
  settings:
    wsl_v5:
      allow-first-in-block: true
      allow-whole-block: false
      branch-max-lines: 2
linters-settings:
  revive:
    rules:
      - name: var-naming
        severity: warning
        arguments:
          - ["ID", "URL"]
